pipeline{
    agent{
        label "node"
    }
    stages{
        stage("checkout"){
            steps{
                git url:'https://github.com/AndyJCheng/lambda-apigateway.git'
            }
        }
        stage("unittest"){
            steps{
                dir("test"){
                     git url:'https://github.com/JohnRDoe/PythonTests1.git'
                     sh 'pytest -v test_sort.py --html=index.html'
                }
            }
            post{
              always{
                  publishHTML(
                      [allowMissing: false, 
                      alwaysLinkToLastBuild: false, 
                      keepAll: false, 
                      reportDir: 'test', 
                      reportFiles: 'index.html', 
                      reportName: 'HTML Report', 
                      reportTitles: ''])
              }
          }

        }
        stage("sonarqube"){
            steps{
                sh 'run sonarqube'
            }

        }
        stage("lambda"){
            steps{

            }

        }
        stage("api-gateway"){
            steps{

            }

        }
    }
}