pipeline{
    agent{
        label "master"
    }
    stages{
        stage("checkout"){
            steps{
                git url:'https://github.com/AndyJCheng/lambda-apigateway.git'
            }
        }
        stage("sonarqube"){
            steps{
                echo 'run sonarqube'
            }

        }
        stage("unittest"){
            steps{
               
                sh 'pytest lambda_test.py --html=index.html'
                publishHTML(
                      [allowMissing: false, 
                      alwaysLinkToLastBuild: false, 
                      keepAll: false, 
                      reportDir: '', 
                      reportFiles: 'index.html', 
                      reportName: 'HTML Report', 
                      reportTitles: 'Report'])
                }
            }
           
        stage("package"){
            steps{
                sh 'zip -r lambda_sample.zip lambda_sample.py'
            }
        }
        stage("lambda"){
            steps{
                dir('/root/lambda-apigateway/lambda'){
                    sh "cp -rf ${WORKSPACE}/lambda_sample.zip ."
                    sh 'terraform init'
                    sh 'echo yes | terraform apply'
                }
                
            }

        }
        stage("api-gateway"){
            steps{
                dir('/root/lambda-apigateway/api-gateway'){
                    sh "cp -rf ${WORKSPACE}/*.yaml ."
                    sh 'terraform init'
                    sh 'echo yes | terraform apply'
                }               
            }
        }
    }
    post{
        always{
            echo "========clean workspace========"
            cleanWs()
        }
    }
}